using Primordially.Core;

namespace Primordially.PluginCore
{
    /// <summary>
    /// Base interface for all plugins
    /// </summary>
    public interface IPlugin
    {
        /// <summary>
        /// Load the rules for this particular game system
        /// </summary>
        BaseGameRules LoadRules();

        /// <summary>
        /// Return an appropriate view model object for a character.
        ///
        /// The character will have been generated by the <see cref="BaseGameRules.CreateCharacter"/>
        /// by the rules returned by <see cref="LoadRules"/>.  Or a character loaded from a previously
        /// saved character of the same
        /// </summary>
        PluginViewModel GetViewModelForCharacter(Character character);
    }
}